### ISSUE TITLE
Code review #1

### ISSUE THREAD

**Issue by ImLewel** [MrSampy/Shop-Of-Things#1]
- Delete all unnecessary usings in ```Business/Services/```, i.e:
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Services/OrderService.cs#L6-L10
- In ```ProductService.cs```:
"if" looks bad, consider making some Null checker and passing the params? (Maybe for entire project):
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Services/ProductService.cs#L26-L28
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Services/ProductService.cs#L152-L154
- In ```RecommendationService.cs```
The magic number "3" is over there
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Services/RecommendationService.cs#L45-L46
- In ```UserService.cs```
Null checking has a lot of mess over here
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Services/UserService.cs#L27-L29
If you can't make some logic in the get/set of your ```UserModel``` then it`s ok (maybe), but if you can, just limit it in the get/set  and throw exception immediately. You can also count age in that model, why not)
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Services/UserService.cs#L33-L34
- Delete all unnecessary usings in ```Business/Interfaces/```, i.e:
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Business/Interfaces/IReceiptService.cs#L2-L7
- Same goes for ```Models``` and ```Validation```
- Delete all unnecessary usings in ```Data/Entities/```, i.e:
https://github.com/MrSampy/Shop-Of-Things/blob/62b87f7e1d82dab952ab8cb19d25b27f5b1bd45a/ShopOfThings/Data/Entities/Order.cs#L1-L5
- Same goes for ```Data```, ```Interfaces``` and ```Repositories```
- Consider deleting unused usings in ```ShopOfThings.Tests``` (since you may not know whether you will use something it is up to you)
- Same for ```WebApi```

**Comment by MrSampy** [comment]
Thanks!
