### ISSUE TITLE
Code review #2 by Imlewel

### ISSUE THREAD

**Issue by ImLewel** [MrSampy/Shop-Of-Things#2]
- This code violates the DRY principle, it is better to put the necessary parameters into a collection and implement it in a loop
https://github.com/MrSampy/Shop-Of-Things/blob/d438f64238c0c0a4d5be4974882a8b0b0e3b5341/ShopOfThings/WebApi/Startup.cs#L55-L107
- Also there
https://github.com/MrSampy/Shop-Of-Things/blob/d438f64238c0c0a4d5be4974882a8b0b0e3b5341/ShopOfThings/WebApi/Startup.cs#L175-L182

**Comment by MrSampy** [comment]
Thanks!
