### ISSUE TITLE
Code review #4 by ImLewel

### ISSUE THREAD

**Issue by ImLewel** [MrSampy/Shop-Of-Things#4]
In [AutomapperProfile.cs](https://github.com/MrSampy/Shop-Of-Things/blob/c1e03c59234189940e450d23c816da47f46b9b2d/ShopOfThings/Business/Validation/AutomapperProfile%20.cs) you have to reorganize the way you make mappings, especially when you use ReverseMap(), because it can cause bugs during mapping, so you can get unexpected results. Also, this method is not well accepted, e.g. https://github.com/MrSampy/Shop-Of-Things/blob/c1e03c59234189940e450d23c816da47f46b9b2d/ShopOfThings/Business/Validation/AutomapperProfile%20.cs#L43-L48
Overall, everything else seems fine.

**Comment by MrSampy** [comment]
Thanks!
